// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoncotesCountyLib.Migrations
{
    [DbContext(typeof(LoncotesCountyLibDbContext))]
    [Migration("20250425011527_AllowNullOutOfCirculation")]
    partial class AllowNullOutOfCirculation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoncotesCountyLib.Models.Checkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("PatronId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Checkouts");
                });

            modelBuilder.Entity("LoncotesCountyLib.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Scy-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cooking"
                        });
                });

            modelBuilder.Entity("LoncotesCountyLib.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaterialTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OutOfCirculationSince")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MaterialTypeId");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 3,
                            MaterialName = "Lord of the Rings",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(2016, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 5,
                            MaterialName = "The NY Times",
                            MaterialTypeId = 2,
                            OutOfCirculationSince = new DateTime(2020, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 2,
                            MaterialName = "Abraham Lincoln, Vampire Slayer",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(2000, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 4,
                            MaterialName = "Sherlock Holmes",
                            MaterialTypeId = 2,
                            OutOfCirculationSince = new DateTime(2015, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 4,
                            MaterialName = "Bethovens 5th",
                            MaterialTypeId = 3,
                            OutOfCirculationSince = new DateTime(1989, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 1,
                            MaterialName = "Isaac Hayes",
                            MaterialTypeId = 4,
                            OutOfCirculationSince = new DateTime(1997, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 1,
                            MaterialName = "The Expanse",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(2015, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 3,
                            MaterialName = "Dungeon Crawler Carl",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(2017, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 3,
                            MaterialName = "Good Charlotte",
                            MaterialTypeId = 3,
                            OutOfCirculationSince = new DateTime(2001, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 5,
                            MaterialName = "Paleo Diet",
                            MaterialTypeId = 4,
                            OutOfCirculationSince = new DateTime(2016, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LoncotesCountyLib.Models.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckoutDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaterialTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckoutDays = 7,
                            Name = "Book"
                        },
                        new
                        {
                            Id = 2,
                            CheckoutDays = 3,
                            Name = "Newspaper"
                        },
                        new
                        {
                            Id = 3,
                            CheckoutDays = 5,
                            Name = "CD"
                        },
                        new
                        {
                            Id = 4,
                            CheckoutDays = 5,
                            Name = "8Track"
                        });
                });

            modelBuilder.Entity("LoncotesCountyLib.Models.Patron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patrons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St.",
                            Email = "tom.perkins@mail.com",
                            FirstName = "Tom",
                            IsActive = true,
                            LastName = "Perkins"
                        },
                        new
                        {
                            Id = 2,
                            Address = "134 South St.",
                            Email = "steve.oh@mail.com",
                            FirstName = "Steve",
                            IsActive = true,
                            LastName = "Oh"
                        });
                });

            modelBuilder.Entity("LoncotesCountyLib.Models.Material", b =>
                {
                    b.HasOne("LoncotesCountyLib.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoncotesCountyLib.Models.MaterialType", "MaterialType")
                        .WithMany()
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("MaterialType");
                });
#pragma warning restore 612, 618
        }
    }
}
